# Generated by Django 4.2.3 on 2023-08-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='latitude',
            field=models.FloatField(default=36.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
