# Generated by Django 4.2.3 on 2023-08-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_pointofinterest_latitude_pointofinterest_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='conditions'),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='point_of_interests'),
        ),
        migrations.AlterField(
            model_name='pointofinterestcondition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='point_of_interest_conditions'),
        ),
        migrations.AlterField(
            model_name='pointofinteresttype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='point_of_interest_types'),
        ),
    ]
